---
# Copy Job xml to be used in virtual machine
- name: make tmp directory to place default job files
  sudo: yes
  shell: mkdir -p {{ remote_tmp_folder }}/jobs
  notify:
    - 'Delete Remote Temporary Folder'

- name: make tmp directory to place docker pipeline job files
  sudo: yes
  shell: mkdir -p {{ remote_tmp_folder }}/jobs/docker_pipeline
  notify:
    - 'Delete Remote Temporary Folder'

- include: copy-files.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
