---
# Set configurations for tools
- name: Add jenkins user to docker group
  sudo: True
  user: name=jenkins append=yes groups=docker
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: Set Git Global Name
  sudo: yes
  shell: 'git config --global user.name "{{ git.name }}"'
  when: git.name is defined

- name: Set Git Global Email
  sudo: yes
  shell: 'git config --global user.email "{{ git.email }}"'
  when: git.email is defined

- name: Set Git Default Push Method
  sudo: yes
  shell: git config --global push.default simple
