---
# Hard-restart Jenkins
# Copy Job xml to be used in virtual machine
# Create jobs in jenkins instance

- name: Restarting Jenkins NOW
  sudo: yes
  command: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 restart
  when: installed_plugins.changed
  register: hard_restart

- name: "{{ startup_delay_s | default(45) }}s delay while rebooting Jenkins"
  wait_for: port=8080 delay={{ startup_delay_s | default(45) }}
  when: hard_restart.changed

# Setup Docker Jobs

- name: list all jobs
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 list-jobs All
  register: existing_jobs

- name: list docker jobs to be created
  sudo: yes
  shell: groovy {{ remote_tmp_folder }}/script/jobs.groovy -j '{{ remote_tmp_folder }}/jobs/docker_pipeline'
  when: "target_jenkins_env == 'docker'"
  register: docker_jobs_list

- name: create jobs for docker pipeline
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 create-job {{ item }} < {{ remote_tmp_folder }}/jobs/docker_pipeline/{{ item }}.xml
  with_items: docker_jobs_list.stdout_lines
  when: "existing_jobs.changed and docker_jobs_list is defined and existing_jobs.stdout.find('{{ item }}') == -1 and target_jenkins_env == 'docker'"
  register: docker_jobs_created

# Create build pipeline view

- name: create build pipeline view
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 create-view < {{ remote_tmp_folder }}/views/build_pipeline_view.xml
  when: "target_jenkins_env == 'docker'"
  ignore_errors: True

# Setup Security
- name: setup security
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 groovy {{ remote_tmp_folder }}/script/security.groovy  admins='{{ security.jenkins_admins }}' orgs='{{ security.github_orgNames }}' clientid='{{ security.github_clientId }}' clientsecret='{{ security.github_clientSecret }}'
  when: security.enable_security is defined and security.enable_security
  register: security_setup

- name: Results - Setup Jenkins Security
  debug: var=security_setup.stdout_lines
