---
remote_tmp_folder: /home/vagrant/tmp
local_files_dir: '../../../files'
machine_path: /usr/local/bin
install_postgres: false
install_redis: false
target_jenkins_env: docker
slave:
  # these are apt packges that dont require any extra repositories to be installed
  apt:
    redis:
      - 'libjemalloc1'
    devtools:
      - 'groovy'
    pip:
      - 'libxml2-dev'
      - 'libxslt1-dev'
      - 'python-lxml'
      - 'python-setuptools'
    base:
      - 'build-essential'
      - 'dkms'
      - 'nfs-common'
      - 'openjdk-7-jre'
      - 'openjdk-7-jdk'
      - 'bash'

# install jenkins plugins
plugins:
  # plugins in update center

  - 'ldap'
  - 'translation'
  - 'github'
  - 'github-oauth'
  - 'ghprb'
  - 'nodejs'
  - 'disk-usage'
  - 'metrics-diskusage'
  - 'performance'
  - 'xvfb'
  - 'greenballs'
  - 'robot'
  - 'htmlpublisher'
  - 'ws-cleanup'
  - 'jobConfigHistory'
  - 'groovy'
  - 'groovy-postbuild'
  - 'build-pipeline-plugin'
  - 'build-name-setter'
  - 'postbuild-task'
  - 'port-allocator'
  - 'copy-to-slave'
  - 'docker-plugin'
  - 'docker-build-publish'
  - 'clone-workspace-scm'

  # install plugins using files:
  # - stored on local machine
  # - downloaded via public urls (recommended)
  # - 'https://dl.dropboxusercontent.com/s/n5lmlponr8w4c22/rally-build-notifier.hpi?dl=0'
