---
# Install slave base apt dependencies
- name: Install base apt dependencies
  sudo: yes
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=latest update-cache=yes"
  with_items: slave.apt.base
  when: slave.apt.base is defined

- name: Install base apt dependencies for development
  sudo: yes
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=latest"
  with_items: slave.apt.devtools
  when: slave.apt.devtools is defined
